### ISSUE TITLE
Create Locations From Controller vs php artisan warehouse:make:location

### ISSUE THREAD

**Issue by pointclickreality** [mvdnbrk/warehouse-framework#55]
Hi, is there a way to create locations within the controller instead of the artisan command? 

Something like

$location = Location::create([
'gln' => 'New Location'
'name' => 'My New Stock Location'
]);

something like this would help a ton, because I have an old system with over 1000 locations that i want to transfer those location names over to your system. I hope this makes since.

**Comment by mvdnbrk** [comment]
`Location` is just an Eloquent model. So you could certainly do that with the code you provided yourself.
