### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by MimisK13** [mvdnbrk/warehouse-framework#56]
Hi.

I probably do not understand something from the instructions... So if it is easy for more clarification.

- More detailed installation instructions
- Add .env.example to the repository
- Which versions of Laravel is it compatible with

Thnx

**Comment by mvdnbrk** [comment]
PHP 7.4 / Laravel 7.2 or higher.

This repo contains just the Eloquent models, how to use these can be found in the repo.
This package does not contain any UI.
