### ISSUE TITLE
Unable to install using composer

### ISSUE THREAD

**Issue by lexKiev** [mvdnbrk/warehouse-framework#62]
**Describe the bug**
I'm using Laravel 8.7.1 and want to add warehouse-framework to my project using composer.

After using `composer require mvdnbrk/warehouse-framework` command i got errors

`Problem 1
    - Installation request for mvdnbrk/warehouse-framework ^0.12.0 -> satisfiable by mvdnbrk/warehouse-framework[v0.12.0].
    - Conclusion: remove laravel/framework v8.7.1
    - Conclusion: don't install laravel/framework v8.7.1
    - mvdnbrk/warehouse-framework v0.12.0 requires illuminate/support ^6.0 || ^7.0 -> satisfiable by illuminate/support[6.x-dev, 7.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.27, v6.18.28, v6.18.29, v6.18.3, v6.18.30, v6.18.31, v6.18.32, v6.18.33, v6.18.34, v6.18.35, v6.18.36, v6.18.37, v6.18.38, v6.18.39, v6.18.4, v6.18.40, v6.18.41, v6.18.42, v6.18.43, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.19.0, v6.19.1, v6.2.0, v6.20.0, v6.20.1, v6.20.10, v6.20.11, v6.20.12, v6.20.13, v6.20.14, v6.20.15, v6.20.16, v6.20.17, v6.20.18, v6.20.19, v6.20.2, v6.20.20, v6.20.21, v6.20.22, v6.20.23, v6.20.24, v6.20.25, v6.20.26, v6.20.27, v6.20.28, v6.20.29, v6.20.3, v6.20.30, v6.20.4, v6.20.5, v6.20.6, v6.20.7, v6.20.8, v6.20.9, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.28.2, v7.28.3, v7.28.4, v7.29.0, v7.29.1, v7.29.2, v7.29.3, v7.3.0, v7.30.0, v7.30.1, v7.30.2, v7.30.3, v7.30.4, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2], laravel/framework[6.x-dev, 7.x-dev].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v8.7.1
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.0.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.0.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.0.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.0.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.0.4|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.1.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.10.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.11.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.12.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.13.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.13.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.14.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.15.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.15.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.16.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.17.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.17.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.10|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.11|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.12|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.13|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.14|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.15|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.16|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.17|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.18|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.19|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.20|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.21|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.22|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.23|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.24|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.25|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.26|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.27|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.28|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.29|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.30|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.31|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.32|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.33|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.34|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.35|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.36|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.37|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.38|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.39|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.4|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.40|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.41|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.42|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.43|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.5|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.6|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.7|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.8|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.18.9|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.19.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.19.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.2.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.10|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.11|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.12|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.13|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.14|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.15|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.16|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.17|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.18|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.19|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.20|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.21|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.22|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.23|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.24|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.25|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.26|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.27|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.28|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.29|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.30|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.4|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.5|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.6|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.7|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.8|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.20.9|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.3.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.4.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.5.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.5.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.5.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.6.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.6.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.6.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.7.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v6.8.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.4|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.5|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.6|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.7|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.0.8|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.1.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.1.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.1.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.1.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.10.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.10.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.10.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.10.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.11.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.12.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.13.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.14.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.14.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.15.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.16.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.16.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.17.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.17.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.17.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.18.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.19.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.19.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.2.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.2.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.2.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.20.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.21.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.22.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.22.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.22.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.22.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.22.4|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.23.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.23.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.23.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.24.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.25.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.26.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.26.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.27.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.28.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.28.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.28.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.28.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.28.4|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.29.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.29.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.29.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.29.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.3.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.30.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.30.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.30.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.30.3|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.30.4|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.4.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.5.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.5.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.5.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.6.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.6.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.6.2|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.7.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.7.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.8.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.8.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.9.0|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.9.1|don't install laravel/framework v8.7.1
    - don't install illuminate/support v7.9.2|don't install laravel/framework v8.7.1
    - Can only install one of: laravel/framework[6.x-dev, v8.7.1].
    - Can only install one of: laravel/framework[7.x-dev, v8.7.1].
    - Installation request for laravel/framework (locked at v8.7.1, required as ^8.0) -> satisfiable by laravel/framework[v8.7.1].
`

Here is my composer.json file:
`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3",
        "ext-json": "*",
        "danielme85/laravel-log-to-db": "^2.4",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/jetstream": "^1.3",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.0",
        "livewire/livewire": "^2.0",
        "spatie/laravel-permission": "^4.2",
        "telegram-bot/api": "^2.3",
        "torann/geoip": "^3.0"
    },
    "require-dev": {
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/Helpers/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

 - Warehouse Framework Version: latest
 - Laravel Version: 8.7.1
 - PHP Version: 7.4

**Comment by lexKiev** [comment]
Installation on fresh clean laravel install also not working, any chance to get help with it? seems this package is very usefull

**Comment by mvdnbrk** [comment]
This packages requires Laravel v8.24 or higher.
